### ISSUE TITLE
unit for labels

### ISSUE THREAD

**Issue by JudyMRSD** [jekhor/aerial-cars-dataset#2]
Thank you very much for the dataset! What's the unit for the bounding box?
I would guess "2 0.160416666667 0.64212962963 0.11875 0.0527777777778" means bus object with corner at x =0.160416666667*image width,  y=0.64212962963*image height, bounding box width = 0.11875**image width, bounding box height=0.0527777777778*image height. I plotted the bounding box but looks strange.
Thanks a lot! That's a super helpful dataset! 
<img width="581" alt="screen shot 2018-04-21 at 11 47 31 am" src="https://user-images.githubusercontent.com/21362902/39086237-a416da48-455c-11e8-94bc-7145e337d4d5.png">

**Comment by jekhor** [comment]
X and Y are coordinates of bbox's center.

сб, 21 апр. 2018 г., 19:08 JudyMRSD <notifications@github.com>:
