### ISSUE TITLE
Run dataset on pretrained weights

### ISSUE THREAD

**Issue by JudyMRSD** [jekhor/aerial-cars-dataset#3]
Hello, I'm trying to run your pretrained weights on this dataset, and the prediction results gives some "person" labels. I might be doing something wrong here. Is the following weights and commands the correct ones to use if I wish to reproduce your result on the same dataset?

Thank you very much for your time and help! 

Weights:
https://drive.google.com/drive/folders/1fODck5uqfh3AXFE4ArqGcuPvIbdl7Z97
Yolo3:
https://github.com/jekhor/darknet 
Commands:
./darknet detect cfg/yolov3-aerial.cfg yolov3-aerial.weights ../aerial-cars-dataset/DJI_0005-0078.jpg
Result:
![predictions](https://user-images.githubusercontent.com/21362902/39097354-1d38c1a8-4629-11e8-8ee7-ac8989917f7a.png)

**Comment by jekhor** [comment]
Use 'detector test' instead of 'detect' command (latest has configs hardcoded).

**Comment by JudyMRSD** [comment]
Thank you so much! 
This is the command if anyone needs it in the future: 
./darknet detector test cfg/aerial.data cfg/yolov3-aerial.cfg yolov3-aerial.weights ../aerial-cars-dataset/DJI_0005-0078.jpg
